### ISSUE TITLE
mac check in GCM failed

### ISSUE THREAD

**Issue by Gamaroff** [mibrito707/cordova-plugin-secure-storage-echo#31] opened 2020-01-13 07:53 UTC
My app used the **cordova-plugin-secure-storage** plugin.
We migrated to **cordova-plugin-secure-storage-echo** since the old plugin was failing on Android 10.

When running the app the plugin throws an exception when calling:

```
const storage = await this.secureStorage.create('key_store');
const keys = await storage.get('app_key');
```

The exception is:
```
mac check in GCM failed
```

Any help is much appreciated.

The configuration on my Macbook is:

```
Ionic:

   Ionic CLI          : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, (and 24 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/gamaroff/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v10.17.0 (/usr/local/Cellar/node@10/10.17.0/bin/node)
   npm               : 6.11.3
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125
```

**Comment by hvaughan3** [comment] 2020-01-30 16:51
Seeing the same issue using plain Cordova without Ionic. Only seeing it on certain Android devices (OnePlus for example).

**Comment by Gamaroff** [comment] 2020-01-30 23:28
It seems to be because the encryption method changed from GCM to CCM.
This means data stored in secure storage on the old plugin is not accessible with this one.

**Comment by hvaughan3** [comment] 2020-01-30 23:48
@Gamaroff Thank you for the reply! I will look into that.

**Comment by praveenraji2i** [comment] 2020-02-14 05:35
@hvaughan3 Any update on this?

**Comment by Gamaroff** [comment] 2020-02-14 13:22
I haven't been able to fix it.

**Comment by hvaughan3** [comment] 2020-02-14 13:52
@praveenraji2i We still plan to catch the error, clear the credentials, and have them login again manually so we can resave with the new format. But I have not had a chance to try it yet.

**Comment by mibrito707** [comment] 2020-03-04 20:28
Hey guys,
Thanks for reporting it, can you check if this a possible duplicate or related to #34 ? There is a PR opened and pending review to partially fix this.

**Comment by timbru31** [comment] 2020-06-02 15:35
Yes this is a duplicate of #34. GCM and CCM modes for AES are not compatible.

**Closed** 2020-06-06 23:14 UTC
