### ISSUE TITLE
null pointer exception issue

### ISSUE THREAD

**Issue by pmcquay** [mibrito707/cordova-plugin-secure-storage-echo#24] opened 2019-11-18 15:10 UTC
Hello,

We've been getting the below issue in our app on some older phones (the only one I have a report for is a BLU Vivo 5R running android 7, but we have seen users describe the same problem in reviews on things like Samsung S7s). We are unable to reproduce this problem.

java.lang.NullPointerException:
at android.app.Instrumentation.execStartActivity (Instrumentation.java:1516)
  at android.app.Activity.startActivityForResult (Activity.java:4226)
  at org.apache.cordova.CordovaActivity.startActivityForResult (CordovaActivity.java:343)
  at android.app.Activity.startActivityForResult (Activity.java:4185)
  at android.app.Activity.startActivity (Activity.java:4509)
  at android.app.Activity.startActivity (Activity.java:4477)
  at com.crypho.plugins.SecureStorage.startActivity (SecureStorage.java:298)
  at com.crypho.plugins.SecureStorage.access$500 (SecureStorage.java:21)
  at com.crypho.plugins.SecureStorage$4.run (SecureStorage.java:230)
  at android.os.Handler.handleCallback (Handler.java:836)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6269)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)

Our app is using the latest version of this plugin. Has anyone else seen this? Have a reproduction? Suggestions?

**Comment by mibrito707** [comment] 2019-11-22 15:17
Hello @pmcquay,
Thanks for reporting it, I'm actually seen that error too, specifically on a Samsung S6.
I do not have steps to reproduce it yet so if you find something please let me know, for now we're troubleshooting the problem to find the solution.

**Comment by mibrito707** [comment] 2019-11-25 15:47
Not a 100 % sure yet, but seems to be related to when user authentication is required and we have to confirm authentication via device credentials, the result of KeyguardManager.createConfirmDeviceCredentialIntent() can be null and we don't handle that result. This PR #25 handles that issue. Still don't know the root cause of why that Intent can be null tough.
I'm gonna close this and reopen if someone finds the root cause and we can fix it.

**Closed by mibrito707** 2019-11-25 15:47 UTC
Labels: bug

**Comment by pmcquay** [comment] 2019-11-28 12:09
I've updated the plugin and released another version of the app, and today we got the below error. This appears to be in a different place, but perhaps it was not happening due to the above error? It happened on a different phone (Oppo A9 2020) in android 9.

java.lang.NullPointerException: 
  at com.crypho.plugins.SecureStorage$1.run (SecureStorage.java:58)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
  at .CPU
  at .14
  at .5
  at 4.4
  at 3.6
  at 2.7
  at 2.1
  at 1.5
  at 1.4
  at .1
  at 0.9
  at 0.9
  at 0.9
  at 0.9
  at 0.8
  at 0.1
  at 0.7
  at 0.7
  at 0.7
  at 0.6
  at 0.5
  at 0.5
  at 0.5
  at 0.5
  at 0.4
  at 0.4
  at 0.3
  at 0.3
  at 0.3
  at 0.3
  at 0.3
  at 0.2
  at 0.2

**Comment by timbru31** [comment] 2020-02-17 14:01
We've had the error in our monitoring, too. Unfortunately, I can't prvoide much details other than the crash report:

```
java.lang.NullPointerException:  
  at com.crypho.plugins.SecureStorage$1.run (SecureStorage.java:60)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
```

Version information:
* Lenovo Lenovo Tab M10 (FHD) (X605L), Android 9
* Plugin v5.0.1

**Comment by timbru31** [comment] 2020-03-05 10:01
Just from looking at the code, there is a null check (https://github.com/mibrito707/cordova-plugin-secure-storage-echo/blob/master/src/android/SecureStorage.java#L52), but the actual call to the `credentialsContext` is made in a new thread (https://github.com/mibrito707/cordova-plugin-secure-storage-echo/blob/master/src/android/SecureStorage.java#L54) - I could imagine that the `credentialsContext` becomes null until the actual code is executed.
